[package]
name = "das_keyboard_github_service"
version = "0.1.0"
authors = ["Mathieu <MathieuKeller@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.8"
actix-service = "2.0.0"
futures = "0.3.16"
env_logger = "0.9.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
json = "0.12.4"
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
openssl = { version = "0.10.35", features = ["vendored"] }

[dev-dependencies]
actix-rt = "2.2.0"
