name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl --all-features --verbose
      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/notifier
      - name: push image
        run: |
          docker login -u=${{ secrets.DOCKER_USER }} -p=${{ secrets.DOCKER_PASSWORD }}
          docker tag ${{ secrets.DOCKER_USER }}/notifier ${{ secrets.DOCKER_USER }}/notifier:latest
          docker push ${{ secrets.DOCKER_USER }}/notifier:latest
          docker tag ${{ secrets.DOCKER_USER }}/notifier ${{ secrets.DOCKER_USER }}/notifier:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USER }}/notifier:${{ github.run_number }}
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'keyboard-notifier'
          stack-definition: 'stack-definition.yaml'
          template-variables: >
            {
              "VERSION": "${{ github.run_number }}", 
              "username": "${{ secrets.DOCKER_USER }}"
            }
        
