name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl --all-features --verbose
      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/notifier
      - name: push image
        run: |
          docker login -u=${{ secrets.DOCKER_USER }} -p=${{ secrets.DOCKER_PASSWORD }}
          docker tag ${{ secrets.DOCKER_USER }}/notifier ${{ secrets.DOCKER_USER }}/notifier:latest
          docker push ${{ secrets.DOCKER_USER }}/notifier:latest
          docker tag ${{ secrets.DOCKER_USER }}/notifier ${{ secrets.DOCKER_USER }}/notifier:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USER }}/notifier:${{ github.run_number }}
        
